[tool.poetry]
name = "clowns"
version = "0.1.0"
description = "Проект, связанный с клоунами"
authors = ["ТВОЙ_ЮЗЕР <твой_имейл@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"
